# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.33.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build and Lint
        run: pnpm build && pnpm lint
  audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.33.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm audit --audit-level high